# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-DMPVmt8JC29JfvLoyewxvdIIJKQBjI
"""

import streamlit as st
import joblib
import numpy as np

# =========================
# LOAD MODEL
# =========================
model = joblib.load('model_rekomendasi.pkl')
scaler = joblib.load('scaler.pkl')
le = joblib.load('label_encoder.pkl')

# =========================
# MAPPING JURUSAN
# =========================
mapping_jurusan = {
    'AKL': 'AKL (Akuntansi dan Keuangan Lembaga)',
    'OTKP': 'OTKP (Otomatisasi dan Tata Kelola Perkantoran)',
    'RPL': 'RPL (Rekayasa Perangkat Lunak)',
    'TKJ': 'TKJ (Teknik Komputer dan Jaringan)',
    'TKR': 'TKR (Teknik Kendaraan Ringan)'
}

# =========================
# UI
# =========================
st.title("🎓 Sistem Rekomendasi Jurusan SMK")
st.write("Masukkan nilai akademik siswa:")

mtk = st.number_input("Nilai Matematika", 0, 100)
ipa = st.number_input("Nilai IPA", 0, 100)
ips = st.number_input("Nilai IPS", 0, 100)
bhs = st.number_input("Nilai Bahasa", 0, 100)

# =========================
# PREDIKSI
# =========================
if st.button("Prediksi Jurusan"):

    # ⚠️ URUTAN HARUS SAMA DENGAN TRAINING
    data = np.array([[mtk, ipa, ips, bhs]])

    data_scaled = scaler.transform(data)
    prediksi = model.predict(data_scaled)
    hasil = le.inverse_transform(prediksi)

    jurusan_lengkap = mapping_jurusan[hasil[0]]

    st.markdown(f"### 🎯 Rekomendasi Jurusan:\n**{jurusan_lengkap}**")